# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decor <- function(seedMat) {
    invisible(.Call(`_SimJoint_decor`, seedMat))
}

SJpearson <- function(X, cor, stochasticStepDomain = as.numeric( c(0, 1)), errorType = "meanSquare", seed = 123L, maxCore = 7L, convergenceTail = 8L, iterLimit = 100000L, verbose = TRUE) {
    .Call(`_SimJoint_SJpearson`, X, cor, stochasticStepDomain, errorType, seed, maxCore, convergenceTail, iterLimit, verbose)
}

SJpearsonPMF <- function(PMFs, sampleSize, cor, stochasticStepDomain = as.numeric( c(0, 1)), errorType = "meanSquare", seed = 123L, maxCore = 7L, convergenceTail = 8L, iterLimit = 100000L, verbose = TRUE) {
    .Call(`_SimJoint_SJpearsonPMF`, PMFs, sampleSize, cor, stochasticStepDomain, errorType, seed, maxCore, convergenceTail, iterLimit, verbose)
}

xSJpearson <- function(X, cor, noise, stochasticStepDomain = as.numeric( c(0, 1)), errorType = "meanSquare", seed = 123L, maxCore = 7L, convergenceTail = 8L, iterLimit = 100000L, verbose = TRUE) {
    .Call(`_SimJoint_xSJpearson`, X, cor, noise, stochasticStepDomain, errorType, seed, maxCore, convergenceTail, iterLimit, verbose)
}

xSJpearsonPMF <- function(PMFs, sampleSize, cor, noise, stochasticStepDomain = as.numeric( c(0, 1)), errorType = "meanSquare", seed = 123L, maxCore = 7L, convergenceTail = 8L, iterLimit = 100000L, verbose = TRUE) {
    .Call(`_SimJoint_xSJpearsonPMF`, PMFs, sampleSize, cor, noise, stochasticStepDomain, errorType, seed, maxCore, convergenceTail, iterLimit, verbose)
}

SJspearman <- function(X, cor, stochasticStepDomain = as.numeric( c(0, 1)), errorType = "meanSquare", seed = 123L, maxCore = 7L, convergenceTail = 8L, iterLimit = 100000L, verbose = TRUE) {
    .Call(`_SimJoint_SJspearman`, X, cor, stochasticStepDomain, errorType, seed, maxCore, convergenceTail, iterLimit, verbose)
}

SJspearmanPMF <- function(PMFs, sampleSize, cor, stochasticStepDomain = as.numeric( c(0, 1)), errorType = "meanSquare", seed = 123L, maxCore = 7L, convergenceTail = 8L, iterLimit = 100000L, verbose = TRUE) {
    .Call(`_SimJoint_SJspearmanPMF`, PMFs, sampleSize, cor, stochasticStepDomain, errorType, seed, maxCore, convergenceTail, iterLimit, verbose)
}

LHSpmf <- function(pmf, sampleSize, seed) {
    .Call(`_SimJoint_LHSpmf`, pmf, sampleSize, seed)
}

exportRandomState <- function(seed) {
    .Call(`_SimJoint_exportRandomState`, seed)
}

